# Generated by Django 5.1.7 on 2025-04-01 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Shoe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('amount', models.IntegerField()),
                ('description', models.TextField(max_length=250)),
                ('image', models.ImageField(upload_to='shoes/')),
            ],
        ),
    ]
