# Generated by Django 5.1.7 on 2025-04-03 18:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shoe',
            name='image',
            field=models.ImageField(upload_to='images/shoes/'),
        ),
        migrations.CreateModel(
            name='Cleaning',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('shoe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='my_app.shoe')),
            ],
        ),
    ]
